### ISSUE TITLE
[1.0.2-4322224] Error when reloading oraxen materials

### ISSUE THREAD

**Issue by noiverre** [promcteam/problockregen#28]
Error log:
```
[04:39:36] [Server thread/INFO]: Could not find material: ORAXEN_orichalcum_ore
[04:39:36] [Server thread/INFO]: [ProBlockRegen] Invalid entry: Invalid material: ORAXEN_orichalcum_ore
[04:39:36] [Server thread/WARN]: java.lang.IllegalArgumentException: Invalid material: ORAXEN_orichalcum_ore
[04:39:36] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[04:39:36] [Server thread/WARN]: 	at ProBlockRegen-1.0.2-4322224.jar//co.marcin.darkrise.riseresources.DataEntry.<init>(DataEntry.java:35)
[04:39:36] [Server thread/WARN]: 	at ProBlockRegen-1.0.2-4322224.jar//co.marcin.darkrise.riseresources.Data.lambda$load$0(Data.java:59)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[04:39:36] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[04:39:36] [Server thread/WARN]: 	at ProBlockRegen-1.0.2-4322224.jar//co.marcin.darkrise.riseresources.Data.load(Data.java:67)
[04:39:36] [Server thread/WARN]: 	at ProBlockRegen-1.0.2-4322224.jar//co.marcin.darkrise.riseresources.RiseResourcesPlugin.reloadConfigs(RiseResourcesPlugin.java:136)
[04:39:36] [Server thread/WARN]: 	at ProBlockRegen-1.0.2-4322224.jar//co.marcin.darkrise.riseresources.CommandExec.onCommand(CommandExec.java:21)
[04:39:36] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[04:39:36] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[04:39:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911)
[04:39:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:874)
[04:39:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:501)
[04:39:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:448)
[04:39:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[04:39:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1173)
[04:39:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[04:39:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[04:39:36] [Server thread/INFO]: [ProBlockRegen] Loaded 0 entries.
[04:39:36] [Server thread/INFO]: Configuration reloaded!
```

Config:
```
towny: false
factionsuuid: false

disabled-regions:
  # If set to true, block regen will only work in these regions
  whitelist: true
  list:
    - region1

disabled-worlds:
  # If set to true, block regen will only work in these worlds
  whitelist: false
  list:
    - world_nether

disable_crop_growth: true
#This will disable melon/pumpkin growth
disable_melon_growth: true
disable_turtle_egg: false
#This will disable bamboo and chorus plants
disable_block_growth: true

entries:
- material: ORAXEN_orichalcum_ore
  break-material: BEDROCK
  #delay is in ticks (20=1s)
  regen-delay: 40
  tool:
    allowed:
    - diamond_pickaxe
    message: "Perlu diamond pickaxe untuk menambang ini!"
    damage: 1
  chance:
    ORAXEN_orichalcum_ore: 1.0
  #If true, drop the mined/broken block/plant
  cancel-drop: false
  # command:
  # - delay: 0
    # as: CONSOLE
    # cmd: say {player}
  # age: 7
```

Oraxen config:
```
orichalcum_ore:
  displayname: <white>Orichalcum Ore
  material: PAPER
  Pack:
    generate_model: true
    custom_model_data: 3000401
    parent_model: block/cube_all
    textures:
    - item/orichalcum_ore.png
  Mechanics:
    noteblock:
      custom_variation: 401
      model: orichalcum_ore
      hardness: 6
      drop:
        silktouch: false
        fortune: false
        minimal_type: DIAMOND
        best_tools:
        - PICKAXE
        loots:
        - oraxen_item: raw_orichalcum
          probability: 1.0


raw_orichalcum:
  displayname: <white>Raw Orichalcum
  material: PAPER
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - item/raw_orichalcum.png
    custom_model_data: 3000102
```

**Comment by Sentropic** [comment]
1.0.2-4322224 is an outdated version. Try the latest dev build in our [Discord Server](https://discord.com/invite/6UzkTe6RvW) and let us know if it still happens :)

**Comment by noiverre** [comment]
> 1.0.2-4322224 is an outdated version. Try the latest dev build in our [Discord Server](https://discord.com/invite/6UzkTe6RvW) and let us know if it still happens :)

I tried the latest build from discord, /version problockregen and /pbr reload log attached below

```java
[02:01:04 INFO]: jwkarsiena issued server command: /pbr reload
[02:01:04 INFO]: Could not find material: ORAXEN_orichalcum_ore
[02:01:04 INFO]: [ProBlockRegen] Invalid entry: Invalid material: ORAXEN_orichalcum_ore
[02:01:04 WARN]: java.lang.IllegalArgumentException: Invalid material: ORAXEN_orichalcum_ore
[02:01:04 WARN]:        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[02:01:04 WARN]:        at ProBlockRegen-1.1.0-2730100.jar//co.marcin.darkrise.riseresources.DataEntry.<init>(DataEntry.java:47)
[02:01:04 WARN]:        at ProBlockRegen-1.1.0-2730100.jar//co.marcin.darkrise.riseresources.Data.lambda$load$0(Data.java:58)
[02:01:04 WARN]:        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[02:01:04 WARN]:        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[02:01:04 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[02:01:04 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[02:01:04 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[02:01:04 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[02:01:04 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[02:01:04 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[02:01:04 WARN]:        at ProBlockRegen-1.1.0-2730100.jar//co.marcin.darkrise.riseresources.Data.load(Data.java:66)
[02:01:04 WARN]:        at ProBlockRegen-1.1.0-2730100.jar//co.marcin.darkrise.riseresources.RiseResourcesPlugin.reloadConfigs(RiseResourcesPlugin.java:143)
[02:01:04 WARN]:        at ProBlockRegen-1.1.0-2730100.jar//co.marcin.darkrise.riseresources.CommandExec.onCommand(CommandExec.java:21)
[02:01:04 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:01:04 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[02:01:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911)
[02:01:04 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[02:01:04 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[02:01:04 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:316)
[02:01:04 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:300)
[02:01:04 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[02:01:04 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$20(PlayerConnection.java:2248)
[02:01:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[02:01:04 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[02:01:04 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:01:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:01:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:01:04 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[02:01:04 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[02:01:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:01:04 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[02:01:04 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[02:01:04 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:01:04 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[02:01:04 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[02:01:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[02:01:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:01:04 INFO]: [ProBlockRegen] Loaded 0 entries.
[02:01:14 INFO]: ProBlockRegen version 1.1.0-2730100
[02:01:14 INFO]: Authors: Travja and GoFlish
```

**Comment by Sentropic** [comment]
External plugin support is only available for the `tools` section right now. Support for Oraxen and ItemsAdder blocks will come in the next update. I'll comment here when it's up :)

**Comment by Sentropic** [comment]
This is solved now in https://github.com/promcteam/problockregen/commit/04279f2583f906c7cb227adea2872d0cb533768d!
